# Generated by Django 2.0.7 on 2019-01-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал прихода/ухода', 'verbose_name_plural': 'Журнал прихода/ухода'},
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='good_operation',
            new_name='goods_operation',
        ),
    ]
