# Generated by Django 2.0.7 on 2019-01-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20190122_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='goods_operation',
        ),
    ]
