# Generated by Django 2.0.7 on 2019-01-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_journal_goods_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='goods_operation',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Уход', 'Уход')], default='Приход', max_length=13),
        ),
    ]
