# Generated by Django 2.0.7 on 2019-01-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_goods_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
