# Generated by Django 2.0.7 on 2019-01-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190122_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=1234567890123, max_length=50),
            preserve_default=False,
        ),
    ]
