# Generated by Django 2.0.7 on 2019-01-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190122_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='good_operation',
            field=models.CharField(choices=[('Приход', 'Приход'), ('Уход', 'Уход')], default='Приход', max_length=13),
        ),
    ]
