# Generated by Django 2.0.7 on 2019-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190122_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
