# Generated by Django 2.0.7 on 2019-01-23 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190123_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_width',
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.Product'),
        ),
    ]
