# Generated by Django 2.0.7 on 2019-01-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190123_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='is_new',
        ),
    ]
